nodeLinker: node-modules

packageExtensions:
  "@vue/cli-service@*":
    dependencies:
      "@babel/core": "^7.0.0"
      "@vue/compiler-sfc": "^3.0.8"
  vue-cli-plugin-vuetify@*:
    peerDependencies:
      webpack: "^4.0.0 || ^5.0.0"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
